<?php

namespace App\Helpers;

class LanguageHelper
{
    protected static $translations = [
        'en' => [
            'site_name' => 'CarePlus Hospital & Research Center',
            'critical_care' => 'CRITICAL CARE: For active medical emergencies, call our 24/7 Hotline:',
            'find_doctors' => 'Doctors',
            'specialties' => 'Departments',
            'services' => 'Services',
            'cabins' => 'Cabins',
            'tests' => 'Diagnostics',
            'equipment' => 'Equipment',
            'video_tour' => 'Hospital Video Tour',
            'locations' => 'Locations',
            'careers' => 'Careers',
            'about_us' => 'About Us',
            'patient_resources' => 'Patient Resources',
            'log_in' => 'Log in',
            'book_now' => 'Book Now',
            'hero_title' => 'Book with Top Specialists & Hospitals.',
            'hero_subtitle' => 'Compassionate Care, Simple Scheduling.',
            'search_placeholder' => 'Enter Doctor, Specialty, or Hospital...',
            'find_now' => 'Find Now',
            'all_locations' => 'All Locations',
            'all_specialties' => 'All Specialties',
            'department_categories' => 'Centers of Excellence & Departments',
            'hospital_highlights' => 'Hospital Specialties & Highlights',
            'featured_doctors' => 'FEATURED SPECIALIST DOCTORS',
            'featured_doctors_sub' => 'Click any doctor card to open full profile & chamber schedule.',
            'book_appointment' => 'Book Appointment',
            'simple_booking_process' => 'SIMPLE BOOKING PROCESS',
            'patient_testimonials' => 'PATIENT TESTIMONIALS & REVIEWS',
            'emergency_help' => 'NEED IMMEDIATE MEDICAL HELP?',
            'emergency_sub' => 'Our 24/7 emergency care and ambulance service are ready.',
            'call_now' => 'CALL NOW: 1-800-CARE-NOW',
            'doctor_consultation' => 'Book Doctor Consultation',
            'patient_name' => 'Patient Name',
            'email_address' => 'Email Address',
            'phone_number' => 'Phone Number',
            'select_doctor' => 'Select Specific Doctor',
            'appointment_date' => 'Preferred Date & Time',
            'confirm_booking' => 'Confirm Doctor Appointment & Get Serial',
            'view_profile' => 'View Profile & Book',
            'degrees' => 'Degrees & Qualifications',
            'consultation_fee' => 'Consultation Fee',
            'chamber_time' => 'Chamber Schedule',
            'room_no' => 'Room Number',
            'daily_rent' => 'Rent Per Day',
            'amenities' => 'Amenities',
            'preparation' => 'Preparation Instructions',
            'serial_no' => 'Serial Number',
            'print_report' => 'Print Doctor Appointment List (PDF/Print)',
            'switch_language' => 'বাংলা',
            'top_rated_network' => 'TOP RATED HEALTHCARE NETWORK',
            'doctors_online' => '50+ DOCTORS ONLINE',
            'explore_dept' => 'Explore Department & Doctors',
            'view_all_doctors' => 'View All Doctors Directory',
            'view_all_departments' => 'View All Departments',
            'step_1_title' => 'Search',
            'step_1_sub' => 'Search specialty, doctor, or hospital profile.',
            'step_2_title' => 'Select Doctor',
            'step_2_sub' => 'Select your preferred certified Doctor.',
            'step_3_title' => 'Choose Time',
            'step_3_sub' => 'Choose convenient time slot for consultation.',
            'step_4_title' => 'Confirm',
            'step_4_sub' => 'Confirm your appointment booking token.',
            'symptoms_notes' => 'Health Symptoms & Notes',

            // 3D Body Symptom Finder Translations
            'body_finder_title' => '3D Interactive Anatomy & Symptom Department Finder',
            'body_finder_subtitle' => 'Click any organ on the 3D body model to discover clinical symptoms & book specialist doctors!',
            'organ_brain' => 'Brain & Head',
            'organ_heart' => 'Heart & Chest',
            'organ_bones' => 'Bones & Spine',
            'organ_lungs' => 'Lungs & Airway',
            'organ_stomach' => 'Stomach & Liver',
            'organ_kidney' => 'Kidneys & Urinary',
            'organ_eyes' => 'Eyes & Vision',
            'organ_pediatric' => 'Pediatrics Body',
        ],
        'bn' => [
            'site_name' => 'কেয়ারপ্লাস হাসপাতাল ও গবেষণা কেন্দ্র',
            'critical_care' => 'জরুরি চিকিৎসাসেবা: যেকোনো মেডিকেল এমার্জেন্সিতে ডায়াল করুন ২৪/৭ হটলাইন:',
            'find_doctors' => 'ডাক্তারগণ',
            'specialties' => 'ডিপার্টমেন্টস',
            'services' => 'সার্ভিসসমূহ',
            'cabins' => 'কেবিনসমূহ',
            'tests' => 'ডায়াগনস্টিকস',
            'equipment' => 'যন্ত্রপাতি',
            'video_tour' => 'হাসপাতাল ভিডিও ট্যুর',
            'locations' => 'শাখাসমূহ',
            'careers' => 'ক্যারিয়ার',
            'about_us' => 'আমাদের সম্পর্কে',
            'patient_resources' => 'রোগীদের তথ্য',
            'log_in' => 'লগইন',
            'book_now' => 'অ্যাপয়েন্টমেন্ট নিন',
            'hero_title' => 'সেরা বিশেষজ্ঞ ডাক্তার ও হাসপাতালে অ্যাপয়েন্টমেন্ট নিন।',
            'hero_subtitle' => 'সহজ বুকিং, নির্ভরযোগ্য ও মানসম্পন্ন চিকিৎসা সেবা।',
            'search_placeholder' => 'ডাক্তারের নাম, বিশেষজ্ঞ বিভাগ বা হাসপাতাল খুঁজুন...',
            'find_now' => 'খুঁজুন',
            'all_locations' => 'সকল লোকেশন',
            'all_specialties' => 'সকল স্পেশালিটি',
            'department_categories' => 'মেডিকেল ডিপার্টমেন্ট ও ইনস্টিটিউট',
            'hospital_highlights' => 'হাসপাতাল স্পেশালিটি ও বিশেষ সুবিধা',
            'featured_doctors' => 'বিশেষজ্ঞ ডাক্তারগণের তালিকা',
            'featured_doctors_sub' => 'ডাক্তারের প্রোফাইল ও চেম্বার সময়সূচী দেখতে যেকোনো ডাক্তার কার্ডে ক্লিক করুন।',
            'book_appointment' => 'অ্যাপয়েন্টমেন্ট নিন',
            'simple_booking_process' => 'সহজ বুকিং প্রক্রিয়া',
            'patient_testimonials' => 'রোগীদের অভিজ্ঞতা ও রিভিউ',
            'emergency_help' => 'জরুরি মেডিকেল সেবার প্রয়োজন?',
            'emergency_sub' => 'আমাদের এম্বুলেন্স ও এমার্জেন্সি মেডিকেল টিম ২৪/৭ প্রস্তুত রয়েছে।',
            'call_now' => 'কল করুন: ১-৮০০-কেয়ার-নাও',
            'doctor_consultation' => 'ডাক্তার কনসালটেশন বুকিং',
            'patient_name' => 'রোগীর নাম',
            'email_address' => 'ইমেইল অ্যাড্রেস',
            'phone_number' => 'ফোন নম্বর',
            'select_doctor' => 'নির্দিষ্ট ডাক্তার নির্বাচন করুন',
            'appointment_date' => 'পছন্দের তারিখ ও সময়',
            'confirm_booking' => 'অ্যাপয়েন্টমেন্ট ও সিরিয়াল নিশ্চিত করুন',
            'view_profile' => 'প্রোফাইল দেখুন ও বুক করুন',
            'degrees' => 'ডিগ্রি ও যোগ্যতা',
            'consultation_fee' => 'পরামর্শ ফি',
            'chamber_time' => 'চেম্বার সময়সূচী',
            'room_no' => 'রুম নম্বর',
            'daily_rent' => 'দৈনিক ভাড়া',
            'amenities' => 'সুযোগ-সুবিধা',
            'preparation' => 'টেস্টের পূর্বপ্রস্তুতি',
            'serial_no' => 'সিরিয়াল নম্বর',
            'print_report' => 'ডাক্তারের অ্যাপয়েন্টমেন্ট তালিকা প্রিন্ট (PDF/Print)',
            'switch_language' => 'English',
            'top_rated_network' => 'শীর্ষমানের স্বাস্থ্যসেবা নেটওয়ার্ক',
            'doctors_online' => '৫০+ ডাক্তার লাইভ সক্রিয়',
            'explore_dept' => 'ডিপার্টমেন্ট ও ডাক্তার তালিকা',
            'view_all_doctors' => 'সকল ডাক্তারদের ডিরেক্টরি',
            'view_all_departments' => 'সকল ডিপার্টমেন্টস',
            'step_1_title' => 'খুঁজুন',
            'step_1_sub' => 'ডাক্তার, বিশেষজ্ঞ বিভাগ বা হাসপাতাল খুঁজুন।',
            'step_2_title' => 'ডাক্তার নির্বাচন',
            'step_2_sub' => 'আপনার পছন্দের নিবন্ধিত ডাক্তার সিলেক্ট করুন।',
            'step_3_title' => 'সময় নির্বাচন',
            'step_3_sub' => 'আপনার সুবিধার সময়সূচী নির্বাচন করুন।',
            'step_4_title' => 'নিশ্চিতকরণ',
            'step_4_sub' => 'আপনার অ্যাপয়েন্টমেন্ট টোকেন কনফার্ম করুন।',
            'symptoms_notes' => 'রোগের লক্ষণ ও স্বাস্থ্য নোটস',

            // 3D Body Symptom Finder Translations
            'body_finder_title' => '৩ডি ইন্টারেক্টিভ মানবদেহের অঙ্গ ও রোগ বিভাগ নির্দেশিকা',
            'body_finder_subtitle' => '৩ডি হিউম্যান মডেলের যেকোনো অঙ্গে ক্লিক করে রোগলক্ষণ ও সঠিক বিশেষজ্ঞ ডাক্তার খুঁজুন!',
            'organ_brain' => 'মস্তিষ্ক ও মাথা',
            'organ_heart' => 'হৃদপিন্ড ও বুক',
            'organ_bones' => 'হাড়, কোমর ও জয়েন্ট',
            'organ_lungs' => 'ফুসফুস ও শ্বাসযন্ত্র',
            'organ_stomach' => 'পাকস্থলী ও লিভার',
            'organ_kidney' => 'কিডনি ও মূত্রনালী',
            'organ_eyes' => 'চোখ ও দৃষ্টিশক্তি',
            'organ_pediatric' => 'শিশু ও নবজাতক',
        ]
    ];

    public static function get($key, $default = null)
    {
        $locale = session('locale', 'en');
        return static::$translations[$locale][$key] ?? static::$translations['en'][$key] ?? $default ?? $key;
    }

    public static function currentLocale()
    {
        return session('locale', 'en');
    }
}
